In [16]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [4]:
# training datasets
x_data = [
    [1,2,1,1],
    [2,1,3,2],
    [3,1,3,4],
    [4,1,5,5],
    [1,7,5,5],
    [1,2,5,6],
    [1,6,6,6],
    [1,7,7,7]
]
y_data = [
    [0,0,1],
    [0,0,1],
    [0,0,1],
    [0,1,0],
    [0,1,0],
    [0,1,0],
    [1,0,0],
    [1,0,0],
]

In [23]:
# Evaluation our model using this test datasets
x_test = [
    [2,1,1],
    [3,1,2],
    [3,3,4]
]
y_test = [
    [0,0,1],
    [0,0,1],
    [0,0,1]
]

In [8]:
X = tf.placeholder("float",[None,3])
Y = tf.placeholder("float",[None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

In [41]:
hypothesis = tf.nn.softmax(tf.matmul(X,W) + b )
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [42]:
#Correct prediction Test model
prediction = tf.arg_max(hypothesis,1)
is_correct = tf.equal(prediction,tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct,tf.float32))

In [43]:
with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val,W_val , _ = sess.run([cost,W,optimizer],feed_dict={ X:x_data , Y:y_data })
        print(step,cost_val,W_val)
    #predict
    print("prediction :",sess.run(prediction,feed_dict={X:x_test}))
    #Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy,feed_dict={X:x_test,Y:y_test}))

0 1.9564581 [[ 0.19595979 -1.348935    0.504431  ]
 [-0.632686   -1.5778795   0.3372595 ]
 [-0.6313934  -0.64137363 -0.34020096]]
1 0.54156274 [[ 0.11146028 -1.3563846   0.5963801 ]
 [-0.67069405 -1.581368    0.37875596]
 [-0.68570465 -0.64537543 -0.2818879 ]]
2 0.31986174 [[ 0.05980625 -1.363365    0.6550146 ]
 [-0.69343215 -1.5846608   0.4047869 ]
 [-0.716869   -0.6490836  -0.24701536]]
3 0.22854376 [[ 0.0229495  -1.3696923   0.6981986 ]
 [-0.7097353  -1.587665    0.4240942 ]
 [-0.7384548  -0.6524198  -0.22209337]]
4 0.17855018 [[-0.00559789 -1.3754396   0.7324933 ]
 [-0.72245824 -1.5904069   0.43955907]
 [-0.7548664  -0.65543437 -0.2026672 ]]
5 0.14686878 [[-0.02884687 -1.3806977   0.7610004 ]
 [-0.73289275 -1.5929246   0.45251125]
 [-0.7680581  -0.6581818  -0.1867281 ]]
6 0.12492714 [[-0.04842913 -1.3855441   0.785429  ]
 [-0.7417352  -1.5952517   0.4636808 ]
 [-0.77906    -0.6607065  -0.17320149]]
7 0.10879848 [[-0.06532579 -1.3900406   0.80682224]
 [-0.74940497 -1.5974158   0.473